server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081


database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: test
  password: test
  url: jdbc:mysql://localhost:3306/aumniassignment?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.hbm2ddl.auto: update

logging:
  level: INFO
  loggers:
    org.aumni: DEBUG
  appenders:
    - type: console
      threshold: INFO
      layout:
        type: json

liquibase:
  changeLogFile: db/changelog/db.changelog-master.xml
  url: jdbc:mysql://localhost:3306/aumniassignment?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  driver: com.mysql.cj.jdbc.Driver
  username: test
  password: test
  loggingLevel: INFO